{
 "title": "ObserveLite Overview",
 "tags": [
  "fastapi",
  "observability",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(request_count_total)", "legendFormat": "requests" }
   ]
  },
  {
   "title": "Request Latency p95",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_bucket[1m])) by (le))",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(error_count_total)", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(request_count_total[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Latency by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_bucket[1m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}} p95"
    }
   ]
  },
  {
   "title": "Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_count_total[1m])) by (endpoint, http_status)",
     "legendFormat": "{{endpoint}} {{http_status}}"
    }
   ]
  }
 ]
}